
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int EXIT = 4;
  public static final int MOD = 8;
  public static final int HISTORY = 6;
  public static final int SIN = 9;
  public static final int PLUS = 15;
  public static final int RPAREN = 23;
  public static final int COS = 10;
  public static final int CLEAR = 5;
  public static final int SQRT = 7;
  public static final int VARIABLE = 3;
  public static final int MODULO = 19;
  public static final int LPAREN = 22;
  public static final int EQUALS = 21;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int DIV = 18;
  public static final int PI = 12;
  public static final int NEWLINE = 13;
  public static final int MINUS = 16;
  public static final int error = 1;
  public static final int TAN = 11;
  public static final int POWER = 20;
  public static final int UMINUS = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "VARIABLE",
  "EXIT",
  "CLEAR",
  "HISTORY",
  "SQRT",
  "MOD",
  "SIN",
  "COS",
  "TAN",
  "PI",
  "NEWLINE",
  "UMINUS",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MODULO",
  "POWER",
  "EQUALS",
  "LPAREN",
  "RPAREN"
  };
}

